Implemented the internationalization
aurelius-adrian/WOIDE-II pull request #9
Opened 2024-12-15 02:44 UTC by asadmasoodchaudhry99

2025-02-25 22:14 UTC, aurelius-adrian requested changes

2025-02-25 22:14 UTC, aurelius-adrian commented on app/[locale]/components/Navbar.tsx
> +            <select
use FluentUI select see taskpane/FormElement code for reference

2025-02-25 22:14 UTC, aurelius-adrian commented on app/[locale]/components/Navbar.tsx
> +const Navbar = ({ locale }: { locale: string }) => {
Check all usages of Navbar; Usage in Setup does not set locale property

2025-02-26 01:51 UTC, asadmasoodchaudhry99 commented on i18n/request.tsx
> +    const locale = requestHeaders.get("X-NEXT-INTL-LOCALE") || "en";
It looks like headers() may not be accessible in the Microsoft Word plugin environment, which prevents requestHeaders.get("X-NEXT-INTL-LOCALE") from retrieving the locale correctly. This results in the locale always defaulting to 'en'. We might need to explore an alternative, such as storing the locale in localStorage or passing it via query parameters. Will Look into it tomorrow

2025-03-04 08:17 UTC, aurelius-adrian approved these changes

2025-03-04 08:18 UTC, merged